apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: test-cred
  namespace: eso-creds-testing-source
spec:
  data:
    - match:
        secretKey: foo
        remoteRef:
          remoteKey: pushed-cred
          property: pushed-foo
  selector:
    secret:
      name: test-secret
  refreshInterval: 5m
  secretStoreRefs:
    - kind: SecretStore
      name: k8s-store-sa-auth
