apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: k8s-store-sa-auth
  namespace: eso-creds-testing-source
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: my-store
      remoteNamespace: eso-creds-testing-target
      server:
        caProvider:
          key: ca.crt
          name: kube-root-ca.crt
          type: ConfigMap
        url: https://kubernetes.default.svc
