apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-cred
  namespace: eso-creds-testing-target
spec:
  data:
  - remoteRef:
      key: test-secret
      property: foo
    secretKey: foo
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: k8s-store-sa-auth
